# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CSProto

import flatbuffers

class AuthList(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAuthList(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AuthList()
        x.Init(buf, n + offset)
        return x

    # AuthList
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AuthList
    def Data(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

def AuthListStart(builder): builder.StartObject(1)
def AuthListAddData(builder, data): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)
def AuthListEnd(builder): return builder.EndObject()
