# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CSProto

import flatbuffers

class AVSubTitle(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAVSubTitle(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AVSubTitle()
        x.Init(buf, n + offset)
        return x

    # AVSubTitle
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AVSubTitle
    def Data(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

def AVSubTitleStart(builder): builder.StartObject(1)
def AVSubTitleAddData(builder, data): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)
def AVSubTitleEnd(builder): return builder.EndObject()
