# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CSProto

import flatbuffers

class ControlMtuR(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsControlMtuR(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ControlMtuR()
        x.Init(buf, n + offset)
        return x

    # ControlMtuR
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ControlMtuR
    def Seg(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ControlMtuR
    def SegLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def ControlMtuRStart(builder): builder.StartObject(1)
def ControlMtuRAddSeg(builder, seg): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(seg), 0)
def ControlMtuRStartSegVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def ControlMtuREnd(builder): return builder.EndObject()
