# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CSProto

import flatbuffers

class ControlIFrame(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsControlIFrame(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ControlIFrame()
        x.Init(buf, n + offset)
        return x

    # ControlIFrame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ControlIFrame
    def Reserved(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def ControlIFrameStart(builder): builder.StartObject(1)
def ControlIFrameAddReserved(builder, reserved): builder.PrependInt8Slot(0, reserved, 0)
def ControlIFrameEnd(builder): return builder.EndObject()
