# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CSProto

import flatbuffers

class InputCursor(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsInputCursor(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InputCursor()
        x.Init(buf, n + offset)
        return x

    # InputCursor
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InputCursor
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # InputCursor
    def Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def InputCursorStart(builder): builder.StartObject(2)
def InputCursorAddX(builder, x): builder.PrependFloat32Slot(0, x, 0.0)
def InputCursorAddY(builder, y): builder.PrependFloat32Slot(1, y, 0.0)
def InputCursorEnd(builder): return builder.EndObject()
