# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CSProto

import flatbuffers

class InputMouseKey(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsInputMouseKey(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InputMouseKey()
        x.Init(buf, n + offset)
        return x

    # InputMouseKey
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InputMouseKey
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # InputMouseKey
    def Pressed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos)
        return 0

def InputMouseKeyStart(builder): builder.StartObject(2)
def InputMouseKeyAddKey(builder, key): builder.PrependUint8Slot(0, key, 0)
def InputMouseKeyAddPressed(builder, pressed): builder.PrependBoolSlot(1, pressed, 0)
def InputMouseKeyEnd(builder): return builder.EndObject()
