# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CSProto

import flatbuffers

class InputMouseMove(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsInputMouseMove(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InputMouseMove()
        x.Init(buf, n + offset)
        return x

    # InputMouseMove
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InputMouseMove
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # InputMouseMove
    def Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

def InputMouseMoveStart(builder): builder.StartObject(2)
def InputMouseMoveAddX(builder, x): builder.PrependInt16Slot(0, x, 0)
def InputMouseMoveAddY(builder, y): builder.PrependInt16Slot(1, y, 0)
def InputMouseMoveEnd(builder): return builder.EndObject()
