# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CSProto

import flatbuffers

class InputMouseWheel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsInputMouseWheel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InputMouseWheel()
        x.Init(buf, n + offset)
        return x

    # InputMouseWheel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InputMouseWheel
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # InputMouseWheel
    def Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

def InputMouseWheelStart(builder): builder.StartObject(2)
def InputMouseWheelAddX(builder, x): builder.PrependInt16Slot(0, x, 0)
def InputMouseWheelAddY(builder, y): builder.PrependInt16Slot(1, y, 0)
def InputMouseWheelEnd(builder): return builder.EndObject()
