# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CSProto

import flatbuffers

class InputTemperature(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsInputTemperature(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InputTemperature()
        x.Init(buf, n + offset)
        return x

    # InputTemperature
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InputTemperature
    def Temperature(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def InputTemperatureStart(builder): builder.StartObject(1)
def InputTemperatureAddTemperature(builder, temperature): builder.PrependFloat32Slot(0, temperature, 0.0)
def InputTemperatureEnd(builder): return builder.EndObject()
