# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CSProto

import flatbuffers

class InputAltimeter(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsInputAltimeter(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InputAltimeter()
        x.Init(buf, n + offset)
        return x

    # InputAltimeter
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InputAltimeter
    def Altitude(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # InputAltimeter
    def Pressure(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def InputAltimeterStart(builder): builder.StartObject(2)
def InputAltimeterAddAltitude(builder, altitude): builder.PrependFloat32Slot(0, altitude, 0.0)
def InputAltimeterAddPressure(builder, pressure): builder.PrependFloat32Slot(1, pressure, 0.0)
def InputAltimeterEnd(builder): return builder.EndObject()
