# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CSProto

import flatbuffers

class OutputVibration(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsOutputVibration(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OutputVibration()
        x.Init(buf, n + offset)
        return x

    # OutputVibration
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OutputVibration
    def L(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # OutputVibration
    def R(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def OutputVibrationStart(builder): builder.StartObject(2)
def OutputVibrationAddL(builder, l): builder.PrependUint16Slot(0, l, 0)
def OutputVibrationAddR(builder, r): builder.PrependUint16Slot(1, r, 0)
def OutputVibrationEnd(builder): return builder.EndObject()
