# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CSProto

import flatbuffers

class AVAudio(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAVAudio(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AVAudio()
        x.Init(buf, n + offset)
        return x

    # AVAudio
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AVAudio
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # AVAudio
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def AVAudioStart(builder): builder.StartObject(1)
def AVAudioAddData(builder, data): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)
def AVAudioStartDataVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def AVAudioEnd(builder): return builder.EndObject()
