# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CSProto

import flatbuffers

class AVVideo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAVVideo(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AVVideo()
        x.Init(buf, n + offset)
        return x

    # AVVideo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AVVideo
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # AVVideo
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def AVVideoStart(builder): builder.StartObject(1)
def AVVideoAddData(builder, data): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)
def AVVideoStartDataVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def AVVideoEnd(builder): return builder.EndObject()
