# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CSProto

import flatbuffers

class ControlScreen(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsControlScreen(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ControlScreen()
        x.Init(buf, n + offset)
        return x

    # ControlScreen
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ControlScreen
    def Zoom(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def ControlScreenStart(builder): builder.StartObject(1)
def ControlScreenAddZoom(builder, zoom): builder.PrependFloat32Slot(0, zoom, 0.0)
def ControlScreenEnd(builder): return builder.EndObject()
