# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CSProto

import flatbuffers

class ControlApp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsControlApp(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ControlApp()
        x.Init(buf, n + offset)
        return x

    # ControlApp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ControlApp
    def App(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

def ControlAppStart(builder): builder.StartObject(1)
def ControlAppAddApp(builder, app): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(app), 0)
def ControlAppEnd(builder): return builder.EndObject()
