# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CSProto

import flatbuffers

class InputProximity(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsInputProximity(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InputProximity()
        x.Init(buf, n + offset)
        return x

    # InputProximity
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InputProximity
    def Proximity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos)
        return 0

def InputProximityStart(builder): builder.StartObject(1)
def InputProximityAddProximity(builder, proximity): builder.PrependBoolSlot(0, proximity, 0)
def InputProximityEnd(builder): return builder.EndObject()
