# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CSProto

import flatbuffers

class InputString(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsInputString(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InputString()
        x.Init(buf, n + offset)
        return x

    # InputString
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InputString
    def Str(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

def InputStringStart(builder): builder.StartObject(1)
def InputStringAddStr(builder, str): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(str), 0)
def InputStringEnd(builder): return builder.EndObject()
