# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CSProto

import flatbuffers

class InputMagnetometer(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsInputMagnetometer(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InputMagnetometer()
        x.Init(buf, n + offset)
        return x

    # InputMagnetometer
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InputMagnetometer
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # InputMagnetometer
    def Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # InputMagnetometer
    def Z(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def InputMagnetometerStart(builder): builder.StartObject(3)
def InputMagnetometerAddX(builder, x): builder.PrependFloat32Slot(0, x, 0.0)
def InputMagnetometerAddY(builder, y): builder.PrependFloat32Slot(1, y, 0.0)
def InputMagnetometerAddZ(builder, z): builder.PrependFloat32Slot(2, z, 0.0)
def InputMagnetometerEnd(builder): return builder.EndObject()
