# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CSProto

import flatbuffers

class ShakeOnline(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsShakeOnline(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ShakeOnline()
        x.Init(buf, n + offset)
        return x

    # ShakeOnline
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ShakeOnline
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # ShakeOnline
    def Token(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # ShakeOnline
    def Server(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # ShakeOnline
    def App(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # ShakeOnline
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ShakeOnlineStart(builder): builder.StartObject(5)
def ShakeOnlineAddId(builder, id): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)
def ShakeOnlineAddToken(builder, token): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(token), 0)
def ShakeOnlineAddServer(builder, server): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(server), 0)
def ShakeOnlineAddApp(builder, app): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(app), 0)
def ShakeOnlineAddType(builder, type): builder.PrependInt32Slot(4, type, 0)
def ShakeOnlineEnd(builder): return builder.EndObject()
