# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CSProto

import flatbuffers

class TouchInfo(object):
    __slots__ = ['_tab']

    # TouchInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TouchInfo
    def X(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # TouchInfo
    def Y(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # TouchInfo
    def Force(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateTouchInfo(builder, x, y, force):
    builder.Prep(4, 12)
    builder.PrependFloat32(force)
    builder.PrependInt32(y)
    builder.PrependInt32(x)
    return builder.Offset()
